export const fakeDb = {
  events: [
    {
      eventId: 1,
      title: "Festival Indie",
      subtitle: "Música en vivo y bandas locales",
      date: "2026-03-20T21:00:00Z",
      piggyBank: true,
      geo: "4.649688123022395; -74.07693546948445; Colombia",
      eventCategoryValues: [
        {
          id: 1,
          name: "Música",
          eventId: 1,
          categoryId: 1,
          valueId: 1,
          value: {
            categoryId: 1,
            valueId: 2,
            value: "string",
          },
          category: {
            categoryId: 2,
            name: "string",
          },
        },
        {
          id: 2,
          name: "Festival",
          eventId: 1,
          categoryId: 2,
          valueId: 2,
          value: {
            categoryId: 1,
            valueId: 2,
            value: "string",
          },
          category: {
            categoryId: 2,
            name: "string",
          },
        },
        {
          id: 3,
          name: "Tecnología",
          eventId: 1,
          categoryId: 3,
          valueId: 3,
          value: {
            categoryId: 1,
            valueId: 2,
            value: "string",
          },
          category: {
            categoryId: 2,
            name: "string",
          },
        },
      ],
      description:
        "Un festival indie con las mejores bandas emergentes de la zona.",
      type: "paid" as "free" | "paid",
      feeRD: 5,
      transferCost: 2,
      feePB: 3,
      commission: 10,
      discountCode: "INDIE10",
      discountType: "PERCENTAGE",
      discount: 10,
      maxDate: "2026-03-20T20:00:00Z",
      maxPurchase: 4,
      timeOut: 15,
      isActive: true,
      labels: [
        { labelId: 1, name: "Música", icon: "music" },
        { labelId: 2, name: "Presencial", icon: "map-pin" },
      ],
    },
    {
      eventId: 2,
      title: "Tech Meetup",
      subtitle: "React, UX y Performance",
      date: "2026-04-05T18:30:00Z",
      piggyBank: false,
      geo: "4.649688123022395; -74.07693546948445; Buenos Aires",
      eventCategoryValues: [
        {
          id: 1,
          name: "Música",
          eventId: 1,
          categoryId: 1,
          valueId: 1,
          value: {
            categoryId: 1,
            valueId: 2,
            value: "string",
          },
          category: {
            categoryId: 2,
            name: "string",
          },
        },
        {
          id: 2,
          name: "Festival",
          eventId: 1,
          categoryId: 2,
          valueId: 2,
          value: {
            categoryId: 1,
            valueId: 2,
            value: "string",
          },
          category: {
            categoryId: 2,
            name: "string",
          },
        },
        {
          id: 3,
          name: "Tecnología",
          eventId: 1,
          categoryId: 3,
          valueId: 3,
          value: {
            categoryId: 1,
            valueId: 2,
            value: "string",
          },
          category: {
            categoryId: 2,
            name: "string",
          },
        },
      ],
      description:
        "Encuentro para desarrolladores frontend con charlas y networking.",
      type: "free" as "free" | "paid",
      feeRD: 0,
      transferCost: 0,
      feePB: 0,
      discountCode: "",
      discountType: "",
      discount: 0,
      maxDate: "2026-04-05T18:00:00Z",
      maxPurchase: 1,
      timeOut: 10,
      isActive: true,
      labels: [{ labelId: 3, name: "Tech", icon: "code" }],
    },
  ],

  ticketTypes: [
    {
      id: 1,
      ticketTypeId: 1,
      eventId: 1,
      name: "General",
      count: 500,
      limit: 4,
      maxDate: "",
      stages: [
        { ticketTypeId: 1, price: 4500, quantity: 200, date: "", dateMax: "", promoterFee: 1 },
        { ticketTypeId: 1, price: 6000, quantity: 300, date: "", dateMax: "", promoterFee: 1 },
      ],
    },
    {
      id: 2,
      ticketTypeId: 2,
      eventId: 1,
      name: "VIP",
      count: 100,
      limit: 2,
      maxDate: "",
      stages: [{ ticketTypeId: 2, price: 9000, quantity: 100, date: "", dateMax: "", promoterFee: 1 }],
    },
    {
      id: 3,
      ticketTypeId: 3,
      eventId: 2,
      name: "Entrada gratuita",
      count: 200,
      limit: 1,
      maxDate: "",
      stages: [{ ticketTypeId: 3, price: 0, quantity: 200, date: "", dateMax: "", promoterFee: 1 }],
    },
  ],

  purchases: [
    {
      purchaseId: 1,
      clientId: 101,
      promoterId: null,
      transferredClientId: null,
      paymentMethod: "BOLD",
      paymentStatus: "PAID",
      totalAmount: 9000,
      partialAmount: null,
      quantity: 2,
      isPartial: false,
      referenceId: "REF-INDIE-001",
      purchaseDate: "2026-02-15T14:22:00Z",
      createdAt: "2026-02-15T14:22:00Z",
      updatedAt: "2026-02-15T14:22:00Z",
      meta: {
        event: { eventId: 1, title: "Festival Indie Junín" },
        changeTickets: null,
      },
    },
  ],

  purchaseTickets: [
    {
      purchaseTicketId: 1,
      purchaseId: 1,
      ticketTypeId: 1,
      status: "READ",
      checkerId: 5,
      isTransferred: false,
      clientId: 101,
      createdAt: "2026-02-15T14:23:00Z",
      updatedAt: "2026-02-15T14:23:00Z",
      qr: "QR-INDIE-001",
      transferredClientId: null,
      ticketType: {
        count: 500,
        ticketTypeId: 1,
        eventId: 1,
        name: "General",
        stages: [{ ticketTypeId: 1, price: 4500, quantity: 200 }],
      },
    },
    {
      purchaseTicketId: 2,
      purchaseId: 1,
      ticketTypeId: 1,
      status: "PENDING",
      checkerId: null,
      isTransferred: false,
      clientId: 101,
      createdAt: "2026-02-15T14:23:10Z",
      updatedAt: "2026-02-15T14:23:10Z",
      qr: "QR-INDIE-002",
      transferredClientId: null,
      ticketType: {
        count: 500,
        ticketTypeId: 1,
        eventId: 1,
        name: "General",
        stages: [{ ticketTypeId: 1, price: 4500, quantity: 200 }],
      },
    },
  ],
};
